version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  assignees:
  - daaveuk
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.2
    - 13.0.3
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.4
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: webpack-manifest-plugin
    versions:
    - 3.1.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
    - 11.0.3
    - 11.0.4
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: workbox-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: "@testing-library/cypress"
    versions:
    - 7.0.3
    - 7.0.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
  - dependency-name: "@fortawesome/react-fontawesome"
    versions:
    - 0.1.14
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: postcss-flexbugs-fixes
    versions:
    - 5.0.2
  - dependency-name: cypress
    versions:
    - 5.6.0
