pull_request_rules:
  - name: merge pull requests from dependabot and daaveuk if CI passes
    conditions:
      - author~=^(dependabot(\\[bot\\])?|daaveuk)$
      - check-success="check"
      - check-success="coverage"
      - check-success="cypress"
      - "#approved-reviews-by>=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
